
namespace IPS {

    /// DO NOT EDIT THIS FILE. Create a new partial class and insert new event into it for your game. 
    /// <summary>
    /// MAKE SURE EACH FIELD HAS UNIQUE VALUE
    /// </summary>
    public partial class SoundEvent {
        public const int None = 0;
        public const int ButtonClicked = 1;
        public const int ButtonDisable = 2;
        public const int Win = 3;
        public const int Lose = 4;
        public const int CurrencyCounting = 5;
        public const int StarCouting = 6;
        public const int NewRank = 7;
        public const int NewUnlocked = 8;
    }
}